DROP DATABASE IF EXISTS burger;
CREATE DATABASE IF NOT EXISTS burger;
USE burger;

CREATE TABLE IF NOT EXISTS burgers (
  id INT NOT NULL UNIQUE AUTO_INCREMENT,
  burger_name VARCHAR(30),
  devoured BOOLEAN NOT NULL
)